apiVersion: v1
data:
  config.yaml: |
    log:
      # The level of logging, can be trace, debug, info, warn, error, fatal
      level: info

    cache:
      enabled: true
kind: ConfigMap
metadata:
  name: daniel-act-runner-configmap
  namespace: gitea
