apiVersion: v1
data:
  config.yaml: "log:\r\n  # The level of logging, can be trace, debug, info, warn,
    error, fatal\r\n  level: info\r\n\r\ncache:\r\n  enabled: false\r\n"
kind: ConfigMap
metadata:
  name: gitea-configmap
  namespace: gitea
