apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: daniel-cache-act-runner-pvc
  namespace: gitea
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
