apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: daniel-act-runner
  name: daniel-act-runner
  namespace: gitea
spec:
  selector:
    matchLabels:
      app: daniel-act-runner
  strategy: {}
  template:
    metadata:
      labels:
        app: daniel-act-runner
    spec:
      containers:
      - env:
        - name: CONFIG_FILE
          value: /etc/act_runner/config.yaml
        - name: GITEA_INSTANCE_URL
          value: https://danicos.dev
        - name: GITEA_RUNNER_LABELS
          value: daniel-act-runner:host
        - name: GITEA_RUNNER_NAME
          value: daniel-act-runner
        - name: GITEA_RUNNER_REGISTRATION_TOKEN
          valueFrom:
            secretKeyRef:
              key: act-runner-daniel-token
              name: gitea-secret
        image: docker.io/gitea/act_runner:latest
        name: daniel-act-runner
        resources: {}
        volumeMounts:
        - mountPath: /etc/act_runner
          name: config
          readOnly: true
        - mountPath: /data
          name: data
        - mountPath: /root/.cache
          name: cache
      volumes:
      - configMap:
          name: gitea-configmap
        name: config
      - name: data
        persistentVolumeClaim:
          claimName: daniel-act-runner-pvc
      - name: cache
        persistentVolumeClaim:
          claimName: daniel-cache-act-runner-pvc
status: {}
