apiVersion: v1
data:
  config.alloy: |
    logging {
      level = "info"
      format = "logfmt"
    }

    loki.write "lokicharlie" {
      endpoint {
        url = "http://loki-gateway.observe.svc.cluster.local/loki/api/v1/push"
      }
    }

    loki.source.journal "systemdcharlie" {
      path = "/var/log/journal"
      relabel_rules = loki.relabel.journal.rules
      labels        = {component = "loki.source.journal"}
      forward_to    = [loki.write.lokicharlie.receiver]
    }

    loki.relabel "journal" {
      forward_to = []

      rule {
        source_labels = ["__journal__systemd_unit"]
        target_label  = "unit"
      }
      rule {
        source_labels = ["__journal__hostname"]
        target_label  = "hostname"
      }
      rule {
        source_labels = ["__journal__systemd_priority"]
        target_label  = "level"
      }
      // Map priority numbers to descriptive names
      rule {
        source_labels = ["__journal__systemd_priority"]
        regex = "0"
        target_label = "level"
        replacement = "emerg"
      }
      rule {
        source_labels = ["__journal__systemd_priority"]
        regex = "1"
        target_label = "level"
        replacement = "alert"
      }
      rule {
        source_labels = ["__journal__systemd_priority"]
        regex = "2"
        target_label = "level"
        replacement = "crit"
      }
      rule {
        source_labels = ["__journal__systemd_priority"]
        regex = "3"
        target_label = "level"
        replacement = "err"
      }
      rule {
        source_labels = ["__journal__systemd_priority"]
        regex = "4"
        target_label = "level"
        replacement = "warning"
      }
      rule {
        source_labels = ["__journal__systemd_priority"]
        regex = "5"
        target_label = "level"
        replacement = "notice"
      }
      rule {
        source_labels = ["__journal__systemd_priority"]
        regex = "6"
        target_label = "level"
        replacement = "info"
      }
      rule {
        source_labels = ["__journal__systemd_priority"]
        regex = "7"
        target_label = "level"
        replacement = "debug"
      }
      // Optional: Filter out noisy kernel messages if desired
      rule {
        source_labels = ["__journal__systemd_unit"]
        regex = "kernel"
        action = "drop"
      }
    }

    // discovery.kubernetes allows you to find scrape targets from Kubernetes resources.
    // It watches cluster state and ensures targets are continually synced with what is currently running in your cluster.
    discovery.kubernetes "pod" {
      role = "pod"
    }

    // discovery.relabel rewrites the label set of the input targets by applying one or more relabeling rules.
    // If no rules are defined, then the input targets are exported as-is.
    discovery.relabel "pod_logs" {
      targets = discovery.kubernetes.pod.targets

      // Label creation - "namespace" field from "__meta_kubernetes_namespace"
      rule {
        source_labels = ["__meta_kubernetes_namespace"]
        action = "replace"
        target_label = "namespace"
      }

      // Label creation - "pod" field from "__meta_kubernetes_pod_name"
      rule {
        source_labels = ["__meta_kubernetes_pod_name"]
        action = "replace"
        target_label = "pod"
      }

      // Label creation - "container" field from "__meta_kubernetes_pod_container_name"
      rule {
        source_labels = ["__meta_kubernetes_pod_container_name"]
        action = "replace"
        target_label = "container"
      }

      // Label creation -  "app" field from "__meta_kubernetes_pod_label_app_kubernetes_io_name"
      rule {
        source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
        action = "replace"
        target_label = "app"
      }

      // Label creation -  "job" field from "__meta_kubernetes_namespace" and "__meta_kubernetes_pod_container_name"
      // Concatenate values __meta_kubernetes_namespace/__meta_kubernetes_pod_container_name
      rule {
        source_labels = ["__meta_kubernetes_namespace", "__meta_kubernetes_pod_container_name"]
        action = "replace"
        target_label = "job"
        separator = "/"
        replacement = "$1"
      }

      // Label creation - "__path__" field from "__meta_kubernetes_pod_uid" and "__meta_kubernetes_pod_container_name"
      // Concatenate values __meta_kubernetes_pod_uid/__meta_kubernetes_pod_container_name.log
      rule {
        source_labels = ["__meta_kubernetes_pod_uid", "__meta_kubernetes_pod_container_name"]
        action = "replace"
        target_label = "__path__"
        separator = "/"
        replacement = "/var/log/pods/*$1/*.log"
      }

      // Label creation -  "container_runtime" field from "__meta_kubernetes_pod_container_id"
      rule {
        source_labels = ["__meta_kubernetes_pod_container_id"]
        action = "replace"
        target_label = "container_runtime"
        regex = `^(\S+):\/\/.+$`
        replacement = "$1"
      }
    }

    // loki.source.kubernetes tails logs from Kubernetes containers using the Kubernetes API.
    loki.source.kubernetes "pod_logs" {
      targets    = discovery.relabel.pod_logs.output
      forward_to = [loki.process.pod_logs.receiver]
    }

    // loki.process receives log entries from other Loki components, applies one or more processing stages,
    // and forwards the results to the list of receivers in the component's arguments.
    loki.process "pod_logs" {
      stage.static_labels {
          values = {
            cluster = "charlie",
          }
      }

      forward_to = [loki.write.lokicharlie.receiver]
    }
kind: ConfigMap
metadata:
  name: alloy-configmap
  namespace: observe
